// ---------------------------------------------------------------------------
// 三国城池 / 关隘 / 港口 数据集
// 坐标采用现代同名地点经纬度（历史城址多在附近，误差可接受）
// kind: city=普通城池, capital=大城/都城, pass=关隘, port=港口/水寨
// tier: 1=大都市 2=重要州治 3=普通郡城 4=关隘小城
// ---------------------------------------------------------------------------
window.SANGUO_SITES = [
  // ---------------- 司隶 / 中原 ----------------
  { id: 'luoyang',   name: '洛阳',  kind: 'capital', tier: 1, lon: 112.454, lat: 34.620, prov: '司隶', region: '中原',
    desc: '东周、东汉、魏、晋皆都于此，天下之中。', guards: ['hulao', 'sishui', 'mengjin'] },
  { id: 'changan',   name: '长安',  kind: 'capital', tier: 1, lon: 108.940, lat: 34.270, prov: '司隶', region: '关中',
    desc: '西汉旧都，沃野千里，被山带河。', guards: ['tongguan', 'wuguan', 'sanguan', 'xiaoguan'] },
  { id: 'hongnong',  name: '弘农',  kind: 'city',    tier: 3, lon: 110.950, lat: 34.520, prov: '司隶', region: '中原', desc: '函谷故地，两京通道。' },
  { id: 'hedong',    name: '安邑',  kind: 'city',    tier: 2, lon: 111.220, lat: 35.030, prov: '司隶', region: '河东', desc: '河东郡治，盐池之利。' },
  { id: 'hulao',     name: '虎牢关', kind: 'pass',   tier: 4, lon: 113.180, lat: 34.845, prov: '司隶', region: '中原', desc: '成皋之险，洛阳东面门户。' },
  { id: 'sishui',    name: '汜水关', kind: 'pass',   tier: 4, lon: 113.240, lat: 34.820, prov: '司隶', region: '中原', desc: '又名虎牢，扼守京畿要冲。' },
  { id: 'mengjin',   name: '孟津',  kind: 'pass',   tier: 4, lon: 112.440, lat: 34.830, prov: '司隶', region: '中原', desc: '黄河津渡，武王会盟之地。' },
  { id: 'tongguan',  name: '潼关',  kind: 'pass',   tier: 4, lon: 110.250, lat: 34.550, prov: '司隶', region: '关中', desc: '关中门户，一夫当关。' },
  { id: 'wuguan',    name: '武关',  kind: 'pass',   tier: 4, lon: 110.620, lat: 33.600, prov: '司隶', region: '关中', desc: '秦楚咽喉，关中东南门户。' },
  { id: 'sanguan',   name: '散关',  kind: 'pass',   tier: 4, lon: 106.950, lat: 34.300, prov: '司隶', region: '关中', desc: '陈仓故道，通汉中之路。' },
  { id: 'xiaoguan',  name: '萧关',  kind: 'pass',   tier: 4, lon: 106.300, lat: 35.600, prov: '司隶', region: '关中', desc: '关中北面屏障。' },
  { id: 'chenliu',   name: '陈留',  kind: 'city',    tier: 2, lon: 114.510, lat: 34.670, prov: '兖州', region: '中原', desc: '曹操起兵之地。' },
  { id: 'puyang',    name: '濮阳',  kind: 'city',    tier: 2, lon: 115.030, lat: 35.710, prov: '兖州', region: '中原', desc: '吕布与曹操鏖战之处。' },
  { id: 'runan',     name: '汝南',  kind: 'city',    tier: 2, lon: 114.350, lat: 33.000, prov: '豫州', region: '中原', desc: '袁氏门生故吏遍布之地。' },
  { id: 'xuchang',   name: '许昌',  kind: 'capital', tier: 1, lon: 113.850, lat: 34.030, prov: '豫州', region: '中原',
    desc: '曹操迎献帝都许，屯田之基。', guards: ['chenliu', 'runan'] },
  { id: 'wan',       name: '宛',    kind: 'city',    tier: 2, lon: 112.530, lat: 32.990, prov: '荆州', region: '南阳', desc: '南阳郡治，光武故乡。' },
  { id: 'luoyang_e', name: '荥阳',  kind: 'city',    tier: 3, lon: 113.380, lat: 34.790, prov: '司隶', region: '中原', desc: '敖仓所在，楚汉相争之地。' },
  { id: 'shangdang', name: '上党',  kind: 'city',    tier: 2, lon: 113.120, lat: 36.200, prov: '并州', region: '山西', desc: '地势高绝，天下之脊。' },
  { id: 'jinyang',   name: '晋阳',  kind: 'city',    tier: 2, lon: 112.540, lat: 37.870, prov: '并州', region: '山西', desc: '并州治所，北面重镇。' },
  { id: 'yanmen',    name: '雁门关', kind: 'pass',   tier: 4, lon: 112.870, lat: 39.330, prov: '并州', region: '山西', desc: '天下九塞之首。' },
  { id: 'hukou',     name: '壶关',  kind: 'pass',   tier: 4, lon: 113.250, lat: 36.100, prov: '并州', region: '山西', desc: '太行陉口，上党门户。' },
  { id: 'ye',        name: '邺',    kind: 'capital', tier: 1, lon: 114.200, lat: 36.340, prov: '冀州', region: '河北',
    desc: '袁绍、曹操皆都于此，铜雀台所在。', guards: ['hukou', 'pingyuan'] },
  { id: 'julu',      name: '巨鹿',  kind: 'city',    tier: 3, lon: 115.030, lat: 37.220, prov: '冀州', region: '河北', desc: '黄巾之乱发源。' },
  { id: 'nanpi',     name: '南皮',  kind: 'city',    tier: 3, lon: 116.710, lat: 38.040, prov: '冀州', region: '河北', desc: '渤海郡治，袁绍起家。' },
  { id: 'pingyuan',  name: '平原',  kind: 'city',    tier: 3, lon: 116.430, lat: 37.160, prov: '青州', region: '河北', desc: '刘备初仕之地。' },
  { id: 'beihai',    name: '北海',  kind: 'city',    tier: 2, lon: 119.120, lat: 36.700, prov: '青州', region: '山东', desc: '孔融治所，郑玄故里。' },
  { id: 'linzi',     name: '临淄',  kind: 'city',    tier: 2, lon: 118.310, lat: 36.830, prov: '青州', region: '山东', desc: '齐都旧地，富庶之邦。' },
  { id: 'jianye',    name: '建业',  kind: 'capital', tier: 1, lon: 118.780, lat: 32.060, prov: '扬州', region: '江东',
    desc: '孙权都城，钟山龙盘，石头虎踞。', guards: ['hefei', 'ruxu', 'chaisang'] },
  { id: 'wu',        name: '吴',    kind: 'city',    tier: 2, lon: 120.620, lat: 31.300, prov: '扬州', region: '江东', desc: '孙氏故乡，富甲东南。' },
  { id: 'kuaiji',    name: '会稽',  kind: 'city',    tier: 2, lon: 120.580, lat: 30.000, prov: '扬州', region: '江东', desc: '山阴大郡，王朗所守。' },
  { id: 'ruxu',      name: '濡须口', kind: 'port',   tier: 4, lon: 117.780, lat: 31.550, prov: '扬州', region: '江淮', desc: '巢湖入江之口，吴魏前线。' },
  { id: 'hefei',     name: '合肥',  kind: 'city',    tier: 2, lon: 117.280, lat: 31.860, prov: '扬州', region: '江淮', desc: '张辽威震逍遥津。' },
  { id: 'shouchun',  name: '寿春',  kind: 'city',    tier: 2, lon: 116.790, lat: 32.580, prov: '扬州', region: '江淮', desc: '袁术称帝之地，淮南重镇。' },
  { id: 'xiaopei',   name: '小沛',  kind: 'city',    tier: 3, lon: 116.940, lat: 34.740, prov: '徐州', region: '中原', desc: '刘备屯兵之所。' },
  { id: 'xiapi',     name: '下邳',  kind: 'city',    tier: 2, lon: 117.960, lat: 34.300, prov: '徐州', region: '中原', desc: '吕布殒命白门楼。' },
  { id: 'xuzhou',    name: '徐州',  kind: 'city',    tier: 2, lon: 117.190, lat: 34.270, prov: '徐州', region: '中原', desc: '陶谦三让徐州。' },
  { id: 'guangling', name: '广陵',  kind: 'city',    tier: 3, lon: 119.420, lat: 32.390, prov: '徐州', region: '江淮', desc: '张纮故里，江淮要冲。' },

  // ---------------- 荆襄 / 两湖 ----------------
  { id: 'xiangyang', name: '襄阳',  kind: 'capital', tier: 1, lon: 112.130, lat: 32.020, prov: '荆州', region: '荆襄',
    desc: '荆州门户，铁打襄阳。', guards: ['fancheng', 'xinye', 'jiangling'] },
  { id: 'fancheng',  name: '樊城',  kind: 'city',    tier: 3, lon: 112.130, lat: 32.060, prov: '荆州', region: '荆襄', desc: '与襄阳隔汉水相望。' },
  { id: 'jiangling', name: '江陵',  kind: 'capital', tier: 1, lon: 112.190, lat: 30.350, prov: '荆州', region: '荆襄',
    desc: '南郡治所，长江中游枢纽。', guards: ['yidu', 'jiangxia'] },
  { id: 'xinye',     name: '新野',  kind: 'city',    tier: 3, lon: 112.360, lat: 32.520, prov: '荆州', region: '荆襄', desc: '刘备屯驻，火烧博望。' },
  { id: 'yidu',      name: '夷陵',  kind: 'pass',   tier: 4, lon: 111.290, lat: 30.700, prov: '荆州', region: '荆襄', desc: '西陵峡口，吴蜀必争。' },
  { id: 'jiangxia',  name: '江夏',  kind: 'city',    tier: 2, lon: 114.310, lat: 30.590, prov: '荆州', region: '荆襄', desc: '黄祖所守，扼长江中游。' },
  { id: 'chaisang',  name: '柴桑',  kind: 'port',   tier: 3, lon: 115.980, lat: 29.700, prov: '扬州', region: '江东', desc: '周瑜练水军之处。' },
  { id: 'xiakou',    name: '夏口',  kind: 'port',   tier: 4, lon: 114.290, lat: 30.600, prov: '荆州', region: '荆襄', desc: '汉水入江之口。' },
  { id: 'changsha',  name: '长沙',  kind: 'city',    tier: 2, lon: 112.940, lat: 28.230, prov: '荆州', region: '荆南', desc: '孙坚起兵之地。' },
  { id: 'wuling',    name: '武陵',  kind: 'city',    tier: 3, lon: 111.700, lat: 29.030, prov: '荆州', region: '荆南', desc: '五溪蛮地。' },
  { id: 'guiyang',   name: '桂阳',  kind: 'city',    tier: 3, lon: 112.730, lat: 25.750, prov: '荆州', region: '荆南', desc: '赵范所守。' },
  { id: 'lingling',  name: '零陵',  kind: 'city',    tier: 3, lon: 111.620, lat: 26.420, prov: '荆州', region: '荆南', desc: '刘度所守。' },
  { id: 'xiangyang2',name: '江津',  kind: 'port',   tier: 4, lon: 111.780, lat: 30.400, prov: '荆州', region: '荆襄', desc: '长江津渡。' },

  // ---------------- 巴蜀 / 汉中 ----------------
  { id: 'chengdu',   name: '成都',  kind: 'capital', tier: 1, lon: 104.066, lat: 30.660, prov: '益州', region: '巴蜀',
    desc: '天府之国，蜀汉都城。', guards: ['mianzhu', 'jiameng', 'bajun'] },
  { id: 'mianzhu',   name: '绵竹',  kind: 'pass',   tier: 4, lon: 104.200, lat: 31.340, prov: '益州', region: '巴蜀', desc: '成都北面最后屏障。' },
  { id: 'jiameng',   name: '剑阁',  kind: 'pass',   tier: 4, lon: 105.530, lat: 32.290, prov: '益州', region: '巴蜀', desc: '剑门天下险，一夫当关。' },
  { id: 'zitong',    name: '梓潼',  kind: 'city',    tier: 3, lon: 105.160, lat: 31.640, prov: '益州', region: '巴蜀', desc: '剑阁之后，涪城之前。' },
  { id: 'bajun',     name: '江州',  kind: 'city',    tier: 2, lon: 106.550, lat: 29.560, prov: '益州', region: '巴蜀', desc: '巴郡治所，两江交汇。' },
  { id: 'fuling',    name: '涪陵',  kind: 'city',    tier: 3, lon: 107.390, lat: 29.700, prov: '益州', region: '巴蜀', desc: '巴东要地。' },
  { id: 'yongan',    name: '永安',  kind: 'pass',   tier: 4, lon: 109.480, lat: 31.020, prov: '益州', region: '巴蜀', desc: '白帝城，刘备托孤处。' },
  { id: 'nanzhong',  name: '建宁',  kind: 'city',    tier: 3, lon: 102.700, lat: 25.030, prov: '益州', region: '南中', desc: '南中腹地，孟获之地。' },
  { id: 'yunnan',    name: '云南',  kind: 'city',    tier: 3, lon: 100.700, lat: 25.450, prov: '益州', region: '南中', desc: '滇池之畔。' },
  { id: 'hanzhong',  name: '汉中',  kind: 'capital', tier: 1, lon: 107.030, lat: 33.070, prov: '益州', region: '汉中',
    desc: '汉高祖王业之基，蜀之门户。', guards: ['jiameng', 'chencang', 'wudu'] },
  { id: 'chencang',  name: '陈仓',  kind: 'pass',   tier: 4, lon: 107.180, lat: 34.360, prov: '益州', region: '汉中', desc: '明修栈道，暗度陈仓。' },
  { id: 'wudu',      name: '武都',  kind: 'city',    tier: 3, lon: 104.930, lat: 33.400, prov: '益州', region: '汉中', desc: '氐羌杂处，陇南要冲。' },
  { id: 'shangyong', name: '上庸',  kind: 'city',    tier: 3, lon: 110.230, lat: 32.070, prov: '荆州', region: '汉中', desc: '汉水上游，孟达所守。' },
  { id: 'xiping',    name: '西平',  kind: 'city',    tier: 3, lon: 101.960, lat: 36.620, prov: '凉州', region: '西凉', desc: '湟水谷地。' },
  { id: 'jincheng',  name: '金城',  kind: 'city',    tier: 3, lon: 103.830, lat: 36.060, prov: '凉州', region: '西凉', desc: '黄河渡口。' },
  { id: 'tianshui',  name: '天水',  kind: 'city',    tier: 2, lon: 105.720, lat: 34.580, prov: '凉州', region: '西凉', desc: '姜维故乡，陇右重镇。' },
  { id: 'wuwei',     name: '武威',  kind: 'city',    tier: 3, lon: 102.640, lat: 37.930, prov: '凉州', region: '西凉', desc: '凉州治所，通西域之路。' },
  { id: 'zhangye',   name: '张掖',  kind: 'city',    tier: 3, lon: 100.450, lat: 38.930, prov: '凉州', region: '西凉', desc: '河西走廊中部。' },
  { id: 'dunhuang',  name: '敦煌',  kind: 'city',    tier: 3, lon: 94.660, lat: 40.140, prov: '凉州', region: '西凉', desc: '华戎所交一大都会。' },
  { id: 'yumen',     name: '玉门关', kind: 'pass',   tier: 4, lon: 93.860, lat: 40.360, prov: '凉州', region: '西凉', desc: '春风不度玉门关。' },
  { id: 'yangping',  name: '阳平关', kind: 'pass',   tier: 4, lon: 106.150, lat: 32.900, prov: '益州', region: '汉中', desc: '汉中西部咽喉。' },

  // ---------------- 江东 / 岭南 ----------------
  { id: 'jianan',    name: '建安',  kind: 'city',    tier: 3, lon: 118.170, lat: 27.050, prov: '扬州', region: '江东', desc: '闽地郡城。' },
  { id: 'panyu',     name: '番禺',  kind: 'city',    tier: 2, lon: 113.260, lat: 23.130, prov: '交州', region: '岭南', desc: '南海郡治，士燮所据。' },
  { id: 'jiaozhi',   name: '龙编',  kind: 'city',    tier: 3, lon: 105.870, lat: 21.050, prov: '交州', region: '岭南', desc: '交趾郡治。' },
  { id: 'cangwu',    name: '苍梧',  kind: 'city',    tier: 3, lon: 111.280, lat: 23.480, prov: '交州', region: '岭南', desc: '西江要冲。' },

  // ---------------- 幽并 / 辽东 ----------------
  { id: 'ji',        name: '蓟',    kind: 'city',    tier: 2, lon: 116.400, lat: 39.900, prov: '幽州', region: '幽燕', desc: '幽州治所，今之北京。' },
  { id: 'zhuojun',   name: '涿郡',  kind: 'city',    tier: 3, lon: 115.980, lat: 39.490, prov: '幽州', region: '幽燕', desc: '刘关张桃园结义处。' },
  { id: 'yuyang',    name: '渔阳',  kind: 'city',    tier: 3, lon: 117.400, lat: 40.100, prov: '幽州', region: '幽燕', desc: '北疆重镇。' },
  { id: 'beiping',   name: '北平',  kind: 'city',    tier: 3, lon: 118.930, lat: 40.600, prov: '幽州', region: '幽燕', desc: '右北平，公孙瓒白马义从。' },
  { id: 'xiangping', name: '襄平',  kind: 'city',    tier: 2, lon: 123.180, lat: 41.270, prov: '幽州', region: '辽东', desc: '辽东郡治，公孙氏割据。' },
  { id: 'liaodong',  name: '辽东',  kind: 'pass',   tier: 4, lon: 119.850, lat: 40.000, prov: '幽州', region: '辽东', desc: '辽西走廊咽喉。' },
  { id: 'daijun',    name: '代郡',  kind: 'city',    tier: 3, lon: 114.100, lat: 40.100, prov: '并州', region: '幽燕', desc: '北出塞外之地。' },
  { id: 'shanggu',   name: '上谷',  kind: 'city',    tier: 3, lon: 115.500, lat: 40.600, prov: '幽州', region: '幽燕', desc: '边塞郡城。' },
  { id: 'juyong',    name: '居庸关', kind: 'pass',   tier: 4, lon: 116.070, lat: 40.290, prov: '幽州', region: '幽燕', desc: '太行八陉之军都陉。' },

  // ---------------- 淮泗 / 青徐 ----------------
  { id: 'xiapi2',    name: '淮阴',  kind: 'city',    tier: 3, lon: 119.020, lat: 33.600, prov: '徐州', region: '江淮', desc: '淮泗之交。' },
  { id: 'anfeng',    name: '安丰',  kind: 'city',    tier: 3, lon: 116.500, lat: 32.400, prov: '扬州', region: '江淮', desc: '芍陂灌溉之利。' },

  // ---------------- 南方 ----------------
  { id: 'nanchang',  name: '南昌',  kind: 'city',    tier: 3, lon: 115.890, lat: 28.680, prov: '扬州', region: '江东', desc: '豫章郡治。' },
  { id: 'changsha2', name: '巴丘',  kind: 'port',   tier: 4, lon: 113.130, lat: 29.370, prov: '荆州', region: '荆南', desc: '洞庭湖畔，鲁肃屯兵。' },
  { id: 'jianning',  name: '永昌',  kind: 'city',    tier: 4, lon: 99.170, lat: 25.110, prov: '益州', region: '南中', desc: '西南极边。' },
];
